image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn install -DskipTests=false && bundle install

vscode:
  extensions:
    - jock.svg@1.3.5:saP8NjiKhPIJgolGEL9E3g==
    - dsznajder.es7-react-js-snippets@2.8.3:MZFzngN6QMMcVWw8QkIFOQ==
    - esbenp.prettier-vscode@5.5.0:xcEnHt0vYXkhJ8IkBmNAuA==
    - mathiasfrohlich.Kotlin@1.7.1:zRxka5i+6/G9r7KC3xmyXQ==